version: "{build}"
platform: x64
branches:
  only:
    - master
skip_tags: true
test: off
deploy: off

environment:
  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

before_build:
  - ps: Install-Product node 5
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))
